Numble3/Paws-Backend

src/main/java/com/numble/team3/account/domain/Account.java
src/main/java/com/numble/team3/account/domain/RoleType.java
src/main/java/com/numble/team3/account/infra/JpaAccountRepository.java
src/main/java/com/numble/team3/config/RedisConfig.java
src/main/java/com/numble/team3/config/SecurityConfig.java
src/main/java/com/numble/team3/security/CustomOAuth2UserService.java
src/main/java/com/numble/team3/security/JwtAuthenticationFilter.java
src/main/java/com/numble/team3/security/OAuth2Attribute.java
src/main/java/com/numble/team3/security/OAuth2SuccessHandler.java
src/main/java/com/numble/team3/sign/application/response/TokenDto.java
src/main/java/com/numble/team3/sign/infra/RedisUtils.java
src/main/resources/application-oauth2.yml
src/main/resources/application.yml

- #3 
- Spring Security oauth2 기본 설정 완료했습니다.
- 패키지 `security`에 추가적으로 코드를 작성했습니다.
- `OAuth2SuccessHandler`에서 회원가입 처리를 하기 위해 `Account` 엔티티 및 리포지토리를 생성했습니다.
- 토큰 관리를 위해 `RedisUtils`와 `RedisConfig`를 추가했습니다. 
- oauth2 관련 설정은 application-oauth2.yml 에 있습니다.
- 현재 파일은 배포 시 테스트 통과를 위한 더미 파일입니다.

[feat] #3 Spring Security oauth2 기본 설정 추가

---

src/main/java/com/numble/team3/account/domain/Account.java
src/main/java/com/numble/team3/account/infra/JpaAccountRepository.java
src/main/java/com/numble/team3/exception/account/AccountEmailAlreadyExistsException.java
src/main/java/com/numble/team3/exception/account/AccountNicknameAlreadyExistsException.java
src/main/java/com/numble/team3/exception/account/AccountNotFoundException.java
src/main/java/com/numble/team3/exception/sign/SignInFailureException.java
src/main/java/com/numble/team3/exception/sign/TokenFailureException.java
src/main/java/com/numble/team3/sign/application/RedisSignService.java
src/main/java/com/numble/team3/sign/application/SignService.java
src/main/java/com/numble/team3/sign/application/advice/SignRestControllerAdvice.java
src/main/java/com/numble/team3/sign/application/mapper/SignUpMapper.java
src/main/java/com/numble/team3/sign/application/request/SignInDto.java
src/main/java/com/numble/team3/sign/application/request/SignUpDto.java
src/main/java/com/numble/team3/sign/controller/SignController.java
src/main/java/com/numble/team3/sign/infra/RedisUtils.java

- #13 
- 회원가입 & 로그인 & 로그아웃 기능을 추가했습니다.
- 패키지 `sign`에 전체적으로 코드를 작성했습니다.
- `mapstruct` 사용을 위해 `Account` 엔티티에 빌더 패턴을 추가했습니다.
- 회원가입 시 중복 체크를 위해 `JpaAccountRepository`에 메소드를 추가했습니다.
- 커스텀 예외는 `exception` 패키지의 도메인 명 패키지 안에 정의했습니다.

[feat] Numble3#13 회원가입 & 로그인 & 로그아웃 기능 추가

---

src/main/java/com/numble/team3/account/domain/Account.java
src/main/java/com/numble/team3/security/OAuth2SuccessHandler.java
src/main/java/com/numble/team3/sign/application/RedisSignService.java
src/main/java/com/numble/team3/sign/application/request/SignUpDto.java

- #17
- 추가 수정
- 현재 `Account`의 경우 기본값으로 `RoleType`을 `RoleType.ROLE_USER`로 가지고 있으므로 기본값을 세팅해 줄 필요가 없습니다.
- 소셜 회원가입 처리 시 `Account`는 `email`, `nickname`, `profile`을 초기화 해야 합니다.
- 일반 회원가입 처리 시 `Account`는 `email`, `nickname`, `password`를 초기화 해야 합니다.
- 두 가지 모두 `String` 타입의 매개변수가 세 개이기 때문에 생성자로 처리할 수 없어 `Account`에 정적 팩토리 메소드를 사용했습니다.
- 기존에는 `MapStruct`을 사용했기 때문에 고려할 필요가 없었지만, 제외하면서 발생한 오류였습니다. 
- `SignService.signUp` 메소드에서 직접 `Account` 엔티티를 생성하는 것을 `dto`를 통해 생성하도록 변경했습니다.
- `SignUpDto`에 `toEntity` 메소드를 추가했습니다.

#17 회원가입 시 비밀번호를 넣지 않는 문제 추가 수정

---

src/main/java/com/numble/team3/security/JwtAuthenticationFilter.java
src/main/java/com/numble/team3/security/OAuth2SuccessHandler.java
src/main/java/com/numble/team3/sign/application/RedisSignService.java
src/main/java/com/numble/team3/sign/controller/SignController.java

- #21 
- `JwtAuthenticationFilter`에서 `Authrization` 헤더에서 `access token`을 추출하도록 수정
- `SignController`
- 쿠키는 `refreshToken`만 생성하도록 수정
- `logout` 시 `Authrization` 헤더에서 `access token`을 추출하도록 수정

[refactor] #21 access token 헤더로 관리 방식 수정

---

src/main/java/com/numble/team3/common/advice/CommonRestControllerAdvice.java
src/main/java/com/numble/team3/exception/account/AccountWithdrawalException.java
src/main/java/com/numble/team3/sign/application/RedisSignService.java
src/main/java/com/numble/team3/sign/application/SignService.java
src/main/java/com/numble/team3/sign/application/advice/SignRestControllerAdvice.java
src/main/java/com/numble/team3/sign/controller/SignController.java

- #24 
- 회원 탈퇴 기능 추가
- `SignController`에 `accountWithdrawal` 메소드를 추가했습니다.
- `SignService`에 `void withdrawal(String accessToken)` 메소드를 추가했습니다.
- `RedisSignService`에 구현했습니다.
- 예외를 처리하는 기능 `RestControllerAdvice` 추가했습니다.
- `/common/advice/CommonRestControllerAdvice`
- `json` 형식에 맞지 않는 경우 발생하는 예외를 처리하는 `RestControllerAdvice` 입니다.
- 전반적으로 필요할 것이라 판단해 `common` 패키지에 추가했습니다.
- `/sign/advice/SignRestControllerAdvice`
- `signController`에서 발생하는 예외를 처리하는 `RestControllerAdvice` 입니다.

[feat] #24 회원 관련 누락 기능 추가

---

build.gradle
src/main/java/com/numble/team3/account/resolver/LoginMethodArgumentResolver.java
src/main/java/com/numble/team3/common/advice/CommonRestControllerAdvice.java
src/main/java/com/numble/team3/common/advice/InvalidParameterDto.java
src/main/java/com/numble/team3/exception/account/AccountWithdrawalException.java
src/main/java/com/numble/team3/sign/application/RedisSignService.java
src/main/java/com/numble/team3/sign/application/SignService.java
src/main/java/com/numble/team3/sign/application/advice/SignRestControllerAdvice.java
src/main/java/com/numble/team3/sign/controller/SignController.java
src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoListDto.java
src/main/java/com/numble/team3/video/domain/Video.java
src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java

- #28 
- Authorization 헤더에서 accessToken 값 추출하도록 수정
- Response Dto의 LocalDateTime을 직렬화하도록 어노테이션 추가
- 관리자 삭제 여부 칼럼 추가, 비디오 리스트 조회 방식 - 페치조인으로 수정
- invalid 파라미터를 보여주도록 컨트롤러 어드바이스 추가

[feat] #28 비디오 도메인 및 LoginArgumentResolver 보완 기능

---

src/main/java/com/numble/team3/config/SecurityConfig.java
src/main/java/com/numble/team3/security/JwtAuthenticationFilter.java
src/main/java/com/numble/team3/security/OAuth2SuccessHandler.java
src/main/java/com/numble/team3/sign/application/RedisSignService.java
src/main/java/com/numble/team3/sign/infra/SignRedisUtils.java

- RedisUtils 이름 변경
- `sign/infra/RedisUtils`의 이름을 `SignRedisUtils`로 변경했습니다.
- 비디오 조회수라거나 회원 마지막 로그인 시간 등 사용해야 할 구간이 많아졌기 때문에 `Sign`에 특화된 이름으로 변경했습니다.

[rename] 기존의 RedisUtils를 SignRedisUtils로 이름 변경

---

src/main/java/com/numble/team3/Team3Application.java
src/main/java/com/numble/team3/account/application/AccountService.java
src/main/java/com/numble/team3/account/domain/Account.java
src/main/java/com/numble/team3/account/infra/AccountRedisUtils.java
src/main/java/com/numble/team3/account/scheduler/AccountLastLoginScheduler.java
src/main/java/com/numble/team3/sign/application/RedisSignService.java

- #30 
- 회원 로그인 시 로그인 시간을 `yyyy.MM.dd` 포맷으로 `Redis`에 저장하고, 매일 자정마다 회원의 마지막 로그인 시간을 업데이트하는 기능을 추가했습니다.
- Account 엔티티가 스스로 상태를 관리할 수 있도록 변경
- 스케쥴러를 사용하기 위해 스프링 부트 메인문에 `@EnableScheduling`를 추가했습니다.
- `Account` 엔티티에 `lastLogin` 필드와 해당 필드를 변경하는 메소드 `changeLastLogin`를 추가했습니다.
- `AccountLastLoginScheduler`를 추가했습니다.
- `AccountRedisUtils`를 추가했습니다.
- `cron`을 활용해 매일 자정마다 동작하도록 설정했습니다.
- `AccountService`를 추가했습니다.
- 스케쥴러에 의해 호출되는 메소드 `changeAccountLastLoginByScheduler`만 정의해놨습니다.
- `RedisSignService`의 `SignIn` 메소드 동작에 `AccountRedisUtils`를 통해 회원의 로그인 시간을 저장하도록 로직을 추가했습니다.
- 충고해 주신대로 Account 엔티티가 스스로 상태를 관리할 수 있도록 `changeLastLogin` 메소드를 변경했습니다.

[feat] 회원 로그인 시간 저장

---

build.gradle
src/main/java/com/numble/team3/exception/image/ImageConvertFailureException.java
src/main/java/com/numble/team3/exception/image/ImageResizeTypeUnSupportException.java
src/main/java/com/numble/team3/exception/image/ImageTypeUnSupportException.java
src/main/java/com/numble/team3/image/application/ApiGatewayImageService.java
src/main/java/com/numble/team3/image/application/ImageService.java
src/main/java/com/numble/team3/image/application/advice/ImageRestControllerAdvice.java
src/main/java/com/numble/team3/image/application/request/CreateImageDto.java
src/main/java/com/numble/team3/image/controller/ImageController.java
src/main/resources/application.yml

- #39 
- `Api Gateway`, `Lambda` 조합으로 처리했습니다.
- 유연한 리사이즈를 위해 리사이즈 타입(`thumbnail`, `profile`)과 이미지 가로, 세로를 필요로 합니다.
- 다음과 같은 과정을 통해 이미지가 리사이즈됩니다.
- 원본 이미지 `s3`에 업로드
- 메타데이터를 `lambda`에서 가져오기 위함입니다.
- 애플리케이션에서 `api gateway` 호출
- `api gateway`가 `lambda` 호출
- `lambda`에서 원본 이미지를 `s3`에서 조회
- `api gateway`에 전달한 정보를 토대로 리사이즈 진행
- 리사이즈 방식에 따라 `s3` 경로에 저장
- 원본 이미지 삭제
- 업로드한 이미지의 경로에 맞는 `cloudfront url` 응답 메세지로 반환

[feat] #39 Image 리사이즈 기능 추가

---

src/main/java/com/numble/team3/common/entity/BaseTimeEntity.java
src/main/java/com/numble/team3/config/QuerydslConfig.java
src/main/java/com/numble/team3/config/WebConfig.java
src/main/java/com/numble/team3/exception/like/LikeNotFoundException.java
src/main/java/com/numble/team3/like/annotation/AddLikeSwagger.java
src/main/java/com/numble/team3/like/annotation/DeleteLikeSwagger.java
src/main/java/com/numble/team3/like/annotation/GetAllLikesSwagger.java
src/main/java/com/numble/team3/like/annotation/GetLikesByCategorySwagger.java
src/main/java/com/numble/team3/like/annotation/GetRankByDaySwagger.java
src/main/java/com/numble/team3/like/application/LikeService.java
src/main/java/com/numble/team3/like/application/RedisLikeService.java
src/main/java/com/numble/team3/like/application/advice/LikeRestControllerAdvice.java
src/main/java/com/numble/team3/like/application/response/GetAllLikeListDto.java
src/main/java/com/numble/team3/like/application/response/GetLikeCategoryListLimitDto.java
src/main/java/com/numble/team3/like/application/response/GetLikeDto.java
src/main/java/com/numble/team3/like/application/response/GetLikeListDto.java
src/main/java/com/numble/team3/like/application/response/GetLikeRankVideoDto.java
src/main/java/com/numble/team3/like/application/response/GetVideoQuerydsl.java
src/main/java/com/numble/team3/like/application/response/GetVideoRankDto.java
src/main/java/com/numble/team3/like/controller/LikeController.java
src/main/java/com/numble/team3/like/domain/Like.java
src/main/java/com/numble/team3/like/infra/CustomJpaLikeRepository.java
src/main/java/com/numble/team3/like/infra/CustomJpaLikeRepositoryImpl.java
src/main/java/com/numble/team3/like/infra/JpaLikeRepository.java
src/main/java/com/numble/team3/like/infra/LikeRedisUtils.java
src/main/java/com/numble/team3/like/scheduler/LikeRankScheduler.java
src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
src/main/resources/application.yml

- #51 
- #40 
- `Like` 관련 기능을 추가했습니다.
- `Querydsl`을 사용하기 위해 `config/QuerydslConfig`를 통해 `JPAQueryFactory`를 빈으로 등록했습니다.
- 중복되는 컬럼인 생성일(`createdAt`)을 공통 처리하기 위해 `common/entity/BaseTimeEntity`를 생성하고 이를 상속받도록 했습니다.
- #47 에서 접근제어자가 `default`여서 외부에서 접근할 수 없길래 `public`으로 수정했습니다.
- 관심영상 관련 페이징 처리를 위해 `application.yml`에 값을 추가했습니다.
- 랭킹을 스케쥴러로 매일 00시 30분에 `redis`에 값을 저장한 이후 조회 시에는 `redis`에서 값을 가져오도록 처리했습니다.
- `Like`에 `Swagger`를 적용시켰습니다.

#51, #40 관심영상(Like) 관련 기능 추가

---

src/main/java/com/numble/team3/converter/application/ApiGatewayConvertService.java
src/main/java/com/numble/team3/converter/application/ConvertService.java
src/main/java/com/numble/team3/converter/domain/ConvertImageUtils.java
src/main/java/com/numble/team3/converter/infra/AwsConvertImageUtils.java

- 이미지 리사이즈 aws 의존성 분리
- 기존에 `ConvertService` 자체에서 관리하던 이미지 관련 aws 의존성을 분리했습니다.
- 단위 테스트 시 `Mockito`가 `private method`까지 `stubbing`을 지원해주지 않았습니다.
- `PowerMock`의 경우 의존성 관련 문제가 발생해 사용할 수 없었습니다.
- 비디오 변환까지 `ApiGatewayConvertService`에서 처리한다면 이미지와 관련된 기능(메타 데이터 추출, 이미지 리사이즈 요청)은 따로 분리하는게 좋다고 판단했습니다.
- `ConvertImageUtils` 인터페이스를 생성하고, 이미지 리사이즈와 관련된 기능을 aws에 의존해서 처리하는 `AwsConvertImageUtils`를 생성했습니다.
- `aws s3` 업로드 시 `IOException`을 단순하게 메소드를 호출한 곳으로 던지는 것이 아닌 커스텀 예외를 던져 `RestControllerAdvice`에서 처리될 수 있도록 했습니다.

[refactor] ApiGatewayConvertService 이미지 리사이즈 aws 의존성 분리

---

src/main/java/com/numble/team3/account/application/AccountService.java
src/main/java/com/numble/team3/account/domain/Account.java
src/main/java/com/numble/team3/account/domain/AccountUtils.java
src/main/java/com/numble/team3/account/infra/AccountRedisUtils.java
src/main/java/com/numble/team3/account/infra/JpaAccountRepository.java
src/main/java/com/numble/team3/admin/annotation/DeleteTokenSwagger.java
src/main/java/com/numble/team3/admin/annotation/GetAccountSwagger.java
src/main/java/com/numble/team3/admin/annotation/GetAccountsSwagger.java
src/main/java/com/numble/team3/admin/annotation/WithdrawalSwagger.java
src/main/java/com/numble/team3/admin/application/advice/AdminAccountRestControllerAdvice.java
src/main/java/com/numble/team3/admin/application/response/GetAccountDetailDto.java
src/main/java/com/numble/team3/admin/application/response/GetAccountListDto.java
src/main/java/com/numble/team3/admin/application/response/GetAccountSimpleDto.java
src/main/java/com/numble/team3/admin/controller/AdminAccountController.java
src/main/java/com/numble/team3/sign/application/SignService.java
src/main/java/com/numble/team3/sign/domain/SignUtils.java
src/main/java/com/numble/team3/sign/infra/RedisSignUtils.java

- #55
- #40 
- `admin` 패키지에 관리자 회우너관리 관련 기능을 추가했습니다.
- `AdminAccountController`에 회원 목록 조회, 회원 단일 조회, 토큰 초기화, 회원 탈퇴 기능을 추가했습니다.
- 관련 `Swagger` 작업을 진행했습니다.

[feat], [docs] 관리자 회원관리 관련 기능 추가

---

src/main/java/com/numble/team3/Team3Application.java
src/main/java/com/numble/team3/common/advice/CommonRestControllerAdvice.java
src/main/java/com/numble/team3/config/SecurityConfig.java
src/main/java/com/numble/team3/config/SwaggerConfig.java
src/main/java/com/numble/team3/like/annotation/AddLikeSwagger.java
src/main/java/com/numble/team3/like/annotation/DeleteLikeSwagger.java
src/main/java/com/numble/team3/like/annotation/GetAllLikesSwagger.java
src/main/java/com/numble/team3/like/annotation/GetLikesByCategorySwagger.java
src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java

- #63 
- `CommenRestControllerAdvice`
- `SecurityConfig`의 내용을 수정했습니다.
- `PathRequest.toStaticResources().atCommonLocations()`를 통해 스프링 부트가 제공하는 static 리소스들의 기본위치 모두 조회해 제외했습니다.
- `Swagger` 설정을 위해 무시하는 배열의 이름을 수정하고, 중복된 부분인 `/webjars/**`를 삭제했습니다.
- `SwaggerConfig`의 내용을 수정했습니다.
- 자동으로 기본 응답을 만들어주는 설정을 비활성화했습니다.
- `@SpringBootApplication`를 수정했습니다.
- `Redis`의 경우 `RedisRepository`를 사용하지 않고 `RedisTemplate`만을 사용하기 때문에 `RedisRepositoriesAutoConfiguration`를 제외했습니다.
- `Like`, `Sign`의 `Swagger` 애노테이션을 수정했습니다.
- `@ApiImplicitParam`의 속성 중 `dataType`을 `dataTypeClass`로 변경했습니다.
- `CommonRestControllerAdvice`에서 모든 예외를 핸들링할 수 있는 메소드를 추가했습니다.

[refactor] #63 Security, Swagger, Redis 설정 수정

---

src/main/java/com/numble/team3/account/annotation/UpdateMyAccountSwagger.java
src/main/java/com/numble/team3/account/application/AccountService.java
src/main/java/com/numble/team3/account/application/advice/AccountRestControllerAdvice.java
src/main/java/com/numble/team3/account/controller/AccountController.java
src/main/java/com/numble/team3/account/infra/JpaAccountRepository.java
src/main/java/com/numble/team3/admin/controller/AdminAccountController.java
src/main/java/com/numble/team3/converter/application/request/CreateImageDto.java
src/main/java/com/numble/team3/sign/controller/SignController.java

- `Account` 수정
- `Admin` 수정
- `Image` 수정
- `Sign` 수정
- 회원 개인정보 수정 시 닉네임 중복체크를 하지 않는 점을 수정했습니다.
- `JpaAccountRepository`에 `findByNickname()`을 추가했습니다.
- `AccountService.updateAccount()`에 닉네임 중복체크 로직을 추가했습니다.
- 관련 `Swagger`도 수정했습니다.
- `AccountService`의 일부 메소드의 이름을 변경했습니다.
- `AdminAccountController`에서 호출한 메소드 이름이 변경되면서 수정사항이 발생했습니다.
- `CreateImageDto`를 수정했습니다.
- `message`의 오타를 수정했습니다.
- `MultipartFile` 타입의 `@Valid`를 `@NotBlank`에서 `@NotNull`로 변경했습니다.
- `SignController`에서 일부 필요없는 `consumes`을 삭제했습니다.
- 헤더만 요청하거나 쿠키만 요청하는 경우

[refactor] Account, Admin, Image, Sign 일부 수정

---

src/test/java/com/numble/team3/account/application/AccountServiceTest.java
src/test/java/com/numble/team3/account/application/request/UpdateMyAccountDtoTest.java
src/test/java/com/numble/team3/account/controller/AccountControllerAdviceTest.java
src/test/java/com/numble/team3/account/controller/AccountControllerTest.java
src/test/java/com/numble/team3/admin/controller/AdminAccountControllerAdviceTest.java
src/test/java/com/numble/team3/admin/controller/AdminAccountControllerTest.java
src/test/java/com/numble/team3/converter/application/ConvertServiceImageTest.java
src/test/java/com/numble/team3/converter/application/request/CreateImageDtoTest.java
src/test/java/com/numble/team3/converter/controller/ConvertControllerAdviceTest.java
src/test/java/com/numble/team3/converter/controller/ConvertControllerImageTest.java
src/test/java/com/numble/team3/factory/UserInfoFactory.java
src/test/java/com/numble/team3/factory/dto/AccountDtoFactory.java
src/test/java/com/numble/team3/factory/dto/ImageDtoFactory.java
src/test/java/com/numble/team3/factory/dto/LikeDtoFactory.java
src/test/java/com/numble/team3/factory/dto/SignDtoFactory.java
src/test/java/com/numble/team3/factory/entity/AccountEntityFactory.java
src/test/java/com/numble/team3/factory/entity/LikeEntityFactory.java
src/test/java/com/numble/team3/factory/entity/VideoEntityFactory.java
src/test/java/com/numble/team3/jwt/JwtProviderTest.java
src/test/java/com/numble/team3/jwt/TokenHelperTest.java
src/test/java/com/numble/team3/like/application/LikeServiceTest.java
src/test/java/com/numble/team3/like/controller/LikeControllerAdviceTest.java
src/test/java/com/numble/team3/like/controller/LikeControllerTest.java
src/test/java/com/numble/team3/sign/application/SignServiceTest.java
src/test/java/com/numble/team3/sign/application/request/SignInDtoTest.java
src/test/java/com/numble/team3/sign/application/request/SignUpDtoTest.java
src/test/java/com/numble/team3/sign/controller/SignControllerAdviceTest.java
src/test/java/com/numble/team3/sign/controller/SignControllerTest.java

- #71 
- 다음 기능에 대한 테스트 코드를 추가했습니다.
- `account`
- `admin` (회원관리)
- `convert` (이미지)
- `like`
- `jwt` 
- `sign`
- 테스트 코드 작성 시 필요한 `DTO`나 `Entity` 생성은 `factory` 패키지 안에 따로 `static 메소드`로 생성했습니다.

[test] 테스트 코드 추가

---

src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/controller/VideoController.java
src/main/java/com/numble/team3/video/domain/VideoUtils.java
src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java
src/main/java/com/numble/team3/video/infra/VideoRedisUtils.java
src/main/java/com/numble/team3/video/scheduler/VideoViewScheduler.java

#61 
- 비디오 상세조회마다 레디스에 조회수를 카운트합니다.
- 매일 2시마다 레디스에 저장된 조회수를 DB에 업데이트합니다.

[feat] #61 비디오 조회수 증가 기능 구현

---

src/main/java/com/numble/team3/comment/application/CommentService.java
src/main/java/com/numble/team3/comment/application/response/GetCommentDto.java
src/main/java/com/numble/team3/comment/application/response/GetCommentListDto.java
src/main/java/com/numble/team3/comment/controller/CommentController.java
src/main/java/com/numble/team3/comment/controller/CommentLikeController.java
src/main/java/com/numble/team3/comment/domain/AccountLikeComment.java
src/main/java/com/numble/team3/comment/domain/Comment.java
src/main/java/com/numble/team3/comment/infra/JpaCommentLikeRepository.java
src/main/java/com/numble/team3/comment/infra/JpaCommentRepository.java

- resolved #0
1. 댓글에 좋아요를 누른 유저들을 관리하기 위해 엔티티를 만들었습니다.
1.1. 해당 엔티티는 댓글에 종속적이라 생각하여 댓글 도메인에 포함시켰습니다.
1.2. 댓글 엔티티를 통해 생성, 삭제를 구현했습니다.
2. 댓글 조회 시 댓글 엔티티 + 댓글 좋아요 엔티티를 조회하기 위한 쿼리를 날리도록 했습니다.
2.1 조회 속도를 빠르게 하기 위해 댓글 엔티티 내부에 좋아요 개수를 카운트하도록 했습니다.
1. 댓글 도메인에 종속적인 개념이 맞을까용?

[Feat] #78 댓글 좋아요 카운트 생성, 삭제, 조회 구현

---

src/main/java/com/numble/team3/sign/controller/SignController.java

- `Cookie` 생성 방식 변경
- 크롬(Google Chrome)80 Cookie 이슈로 인해 프론트엔드에서 쿠키가 저장되지 않는 현상이 발생했습니다.
- `SignController`에서 로그인 했을때와 로그아웃 했을 때의 쿠키를 `ResponseCookie`를 통해 생성하는 것으로 로직을 변경했습니다.
- 현재는 프론트엔드가 배포되지 않은 상태이기 때문에 `domain`을 `localhost`로 설정했습니다.

[refactor] Cookie 생성 방식 변경

---

src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java
src/main/java/com/numble/team3/sign/controller/SignController.java
src/test/java/com/numble/team3/sign/controller/SignControllerAdviceTest.java
src/test/java/com/numble/team3/sign/controller/SignControllerTest.java

- resolved #120 
- `SignController`에서 쿠키와 관련된 로직을 모두 제거했습니다.
- `/api/refresh-token`에서 쿠키로 토큰을 받는 로직을 `Authorization`을 통해 쿠키를 받도록 변경했습니다.
- 관련 `Swagger`, 테스트 코드를 수정했습니다.

[refactor] #120 Sign 쿠키 관련 로직 삭제

---

src/main/java/com/numble/team3/admin/annotation/GetAccountVideosSwagger.java
src/main/java/com/numble/team3/admin/application/response/GetSimpleAccountVideoDto.java

- `Response` `Dto Field` 이름 변경
- `GetSimpleAccountVideoDto`의 `thumbnailPath`를 `thumbnailUrl`로 변경했습니다.

[rename] Response Dto Field 이름 변경

---

src/main/java/com/numble/team3/exception/like/LikeVideoAlreadyExistsException.java
src/main/java/com/numble/team3/like/annotation/AddLikeVideoSwagger.java
src/main/java/com/numble/team3/like/application/LikeVideoService.java
src/main/java/com/numble/team3/like/application/advice/LikeVideoRestControllerAdvice.java
src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java

- 좋아요 추가 시 검증 로직이 없어 중복으로 좋아요가 되는 것을 방지하기 위한 로직 추가
- `addLike` 메소드에서 좋아요가 이미 있는지 검증하는 로직을 추가했습니다.
- `JpaLikeVideoRepository`에 `videoId`와 `accountId`로 존재유무를 확인할 수 있는 `existsLikeByVideoIdAndAccountId` 메소드를 추가했습니다.
- `LikeVideoAlreadyExistsException` 예외를 추가하고, 그에 따라 `RestControllerAdvice`에서 핸들링하도록 내용을 추가했습니다.
- 변경된 사항을 `Swagger`에 적용했습니다.

[refactor] addLike 검증 로직 추가
