scripts/start.sh

#6 빌드 스크립트 수정

---

build.gradle
src/main/java/com/numble/team3/config/SecurityConfig.java
src/main/java/com/numble/team3/config/SwaggerConfig.java

#23 스웨거 연동 설정 추가

---

.gitignore
build.gradle
scripts/start.sh
src/main/java/com/numble/team3/common/infra/S3Uploader.java
src/main/java/com/numble/team3/config/AmazonS3Config.java
src/main/resources/application.yml

S3 연동 및 이미지, 비디오 업로드 함수 추가
#32 
- 변환된 영상 파일을 모두 올리기 위해 특정 디렉토리 내부의 파일들을 모두 S3에 업로드하도록 함수 추가
- 이미지 업로드 함수 추가 (추후 필요에 따라 수정)

[Feat] #32 s3 연동 및 업로드 함수 추가

---

build.gradle
src/main/java/com/numble/team3/config/SecurityConfig.java
src/main/java/com/numble/team3/config/SwaggerConfig.java
src/main/resources/application.yml

- #35 
- `Swagger` 버전을 `3.0.0`으로 변경하면서 필요한 `Swagger` 관련 라이브러리를 추가했습니다.
- 메이저 버전 변경으로 인해 `SecurityConfig`, `application.yml`, `SwaggerConfig`를 수정했습니다.
- `Swagger` 요청 주소가 `http://ip/swagger-ui/`로 변경되었습니다.

[refactor] #35 Swagger 버전 3.0.0으로 변경

---

.gitignore
scripts/start.sh

상대경로로 되어 있는 yml 파일 경로를 절대경로로 변경했습니다.

[bug] #41 배포 스크립트 오타 수정 및 git ignore 수정

---

src/main/java/com/numble/team3/sign/annotation/AccountWithdrawalSwagger.java
src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java
src/main/java/com/numble/team3/sign/annotation/LogoutSwagger.java
src/main/java/com/numble/team3/sign/annotation/SignInSwagger.java
src/main/java/com/numble/team3/sign/annotation/SignUpSwagger.java
src/main/java/com/numble/team3/sign/application/request/SignInDto.java
src/main/java/com/numble/team3/sign/application/request/SignUpDto.java
src/main/java/com/numble/team3/sign/application/response/TokenDto.java
src/main/java/com/numble/team3/sign/controller/SignController.java

- #40 
- `SignController`에 `Swagger`를 추가했습니다.
- `Swagger` 설정은 따로 애노테이션으로 분리했습니다.

[docs] #40 Sign Swagger 추가

---

.gitignore
build.gradle
src/main/java/com/numble/team3/common/infra/S3Uploader.java
src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/controller/VideoController.java
src/main/java/com/numble/team3/video/domain/VideoUtils.java
src/main/java/com/numble/team3/video/infra/VideoFfmpegUtils.java
src/main/resources/application-ffmpeg.yml
src/main/resources/application.yml
src/test/java/com/numble/team3/Team3ApplicationTests.java

#31
- 비디오를 변환하여 .m3u8 파일의 S3 업로드 경로를 DB에 저장하도록 함
- S3 업로드 경로는 UUID 형태로 폴더를 생성하고, .m3u8, .ts파일들을 해당 경로에 업로드
- 남은 디렉토리와 파일들은 지우도록 함

[Feat 31] # 31 비디오 변환 로직 추가

---

src/main/java/com/numble/team3/image/annotation/ImageResizeSwagger.java
src/main/java/com/numble/team3/image/application/request/CreateImageDto.java
src/main/java/com/numble/team3/image/controller/ImageController.java

- #40 
- `ImageController`에 `Swagger`를 추가했습니다.
- `Swagger` 설정은 따로 애노테이션으로 분리했습니다.

[docs] #40 Image Swagger 추가

---

src/main/java/com/numble/team3/comment/application/CommentService.java
src/main/java/com/numble/team3/comment/application/request/CreateOrUpdateCommentDto.java
src/main/java/com/numble/team3/comment/application/response/GetCommentDto.java
src/main/java/com/numble/team3/comment/application/response/GetCommentListDto.java
src/main/java/com/numble/team3/comment/controller/CommentController.java
src/main/java/com/numble/team3/comment/domain/Comment.java
src/main/java/com/numble/team3/comment/infra/JpaCommentRepository.java
src/main/java/com/numble/team3/exception/comment/CommentNotFoundException.java
src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/application/request/CreateOrUpdateVideoDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java
src/main/java/com/numble/team3/video/controller/VideoController.java
src/main/java/com/numble/team3/video/domain/Video.java

- #49 
- 썸네일 이미지의 경로를 비디오 도메인에 저장하는 로직 구현
- 
- 비디오 도메인에 댓글 저장하는 로직 구현

Feat 49 비디오 썸네일 저장 로직 구현, 댓글 CRUD 구현

---

src/main/java/com/numble/team3/converter/application/advice/ConvertRestControllerAdvice.java
src/main/java/com/numble/team3/converter/controller/ConvertController.java

- #56 
- #58 
- 충돌로 인해 누락된 로직 복구
- `ConvertController`에 이미지 리사이징 시 비율을 검증하는 로직을 복구했습니다.
- `ConvertRestControllerAdvice`에 이미지 리사이징 검증 실패 시 발생하는 예외를 핸들링하는 로직을 복구했습니다.

[fix] #56, #58 git 충돌로 인해 누락된 로직 복구

---

src/main/java/com/numble/team3/converter/application/ApiGatewayConvertService.java
src/main/java/com/numble/team3/converter/application/ConvertService.java
src/main/java/com/numble/team3/converter/application/response/GetConvertUrlDto.java
src/main/java/com/numble/team3/converter/application/response/GetConvertVideoDto.java
src/main/java/com/numble/team3/converter/controller/ConvertController.java
src/main/java/com/numble/team3/converter/domain/ConvertVideoUtils.java
src/main/java/com/numble/team3/converter/infra/AwsConvertVideoUtils.java

#64 
- 비디오를 변환하는 api gateway의 응답 dto에 영상 시간을 추가했습니다.
- 비디오 의존성을 분리했습니다.

[fix, refactor] ApiGatewayService 비디오 의존성 분리 및 api gateway에 전달하는 파라미터 수정

---

src/main/java/com/numble/team3/account/annotation/GetMyAccountSwagger.java
src/main/java/com/numble/team3/account/annotation/UpdateMyAccountSwagger.java
src/main/java/com/numble/team3/account/annotation/WithdrawalAccountSwagger.java
src/main/java/com/numble/team3/account/application/AccountService.java
src/main/java/com/numble/team3/account/application/advice/AccountRestControllerAdvice.java
src/main/java/com/numble/team3/account/application/request/UpdateMyAccountDto.java
src/main/java/com/numble/team3/account/application/response/GetMyAccountDto.java
src/main/java/com/numble/team3/account/controller/AccountController.java
src/main/java/com/numble/team3/account/domain/Account.java

- #67 
- #40 
- `account` 패키지에 프로필 관련 기능을 추가했습니다.
- `account` 관련 기능에 `Swagger`를 적용했습니다.

[feat], [docs] 프로필 관련 기능 추가

---

src/main/java/com/numble/team3/comment/application/CommentService.java
src/main/java/com/numble/team3/comment/application/response/GetCommentDto.java
src/main/java/com/numble/team3/comment/application/response/GetCommentListDto.java
src/main/java/com/numble/team3/comment/controller/CommentController.java
src/main/java/com/numble/team3/comment/domain/CommentSortCondition.java
src/main/java/com/numble/team3/comment/infra/JpaCommentRepository.java
src/main/java/com/numble/team3/comment/infra/JpaSearchCommentRepository.java
src/main/java/com/numble/team3/comment/infra/JpaSearchCommentRepositoryImpl.java

1. 댓글 조회 시 인피니티 스크롤을 위한 hasNext에서 발생하는 버그를 수정했습니다.
2. 댓글 조회 시 디폴트는 인기순으로, 최신순을 선택하여 정렬할 수 있습니다.
- resolved #76 
1. 비디오와 동일하게 시분초 포맷을 더 붙였습니다.
2. 페이징 시 1개를 더 조회하여 사이즈보다 크다면 hasNext를 true로 합니다.
3. CommentSortCondition에 따라 정렬 시 인기순, 최신순으로 수행합니다.

[bug, feat] #76 댓글 조회 버그 수정 및 정렬 기능 구현

---

src/main/java/com/numble/team3/admin/application/response/GetVideoDetailForAdminDto.java
src/main/java/com/numble/team3/admin/application/response/GetVideoListForAdminDto.java
src/main/java/com/numble/team3/admin/application/response/GetVideoSimpleForAdminDto.java
src/main/java/com/numble/team3/admin/controller/AdminVideoController.java
src/main/java/com/numble/team3/converter/infra/AwsConvertVideoUtils.java
src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/domain/Video.java

- resolved #82
1. 관리자 동영상 조회, 삭제 기능을 추가했습니다.
2. 동영상 변환 url을 /video -> /video/storage 로 변경했습니다.

[Feat] #82 관리자 동영상 조회, 삭제 기능 추가 및 동영상 변환 url 수정

---

src/main/java/com/numble/team3/admin/annotation/DeleteVideoForAdminSwagger.java
src/main/java/com/numble/team3/admin/annotation/GetAllVideoForAdminSwagger.java
src/main/java/com/numble/team3/admin/annotation/GetDetailVideoForAdminSwagger.java
src/main/java/com/numble/team3/admin/application/response/GetVideoDetailForAdminDto.java
src/main/java/com/numble/team3/admin/application/response/GetVideoListForAdminDto.java
src/main/java/com/numble/team3/admin/application/response/GetVideoSimpleForAdminDto.java
src/main/java/com/numble/team3/admin/controller/AdminVideoController.java
src/main/java/com/numble/team3/comment/annotation/CreateCommentLikeSwagger.java
src/main/java/com/numble/team3/comment/annotation/CreateCommentSwagger.java
src/main/java/com/numble/team3/comment/annotation/DeleteCommentLikeSwagger.java
src/main/java/com/numble/team3/comment/annotation/DeleteCommentSwagger.java
src/main/java/com/numble/team3/comment/annotation/GetAllCommentSwagger.java
src/main/java/com/numble/team3/comment/annotation/PutCommentSwagger.java
src/main/java/com/numble/team3/comment/application/request/CreateOrUpdateCommentDto.java
src/main/java/com/numble/team3/comment/controller/CommentController.java
src/main/java/com/numble/team3/comment/controller/CommentLikeController.java
src/main/java/com/numble/team3/comment/domain/CommentSortCondition.java
src/main/java/com/numble/team3/video/annotation/CreateVideoSwagger.java
src/main/java/com/numble/team3/video/annotation/DeleteVideoSwagger.java
src/main/java/com/numble/team3/video/annotation/GetVideoAllSwagger.java
src/main/java/com/numble/team3/video/annotation/GetVideoDetailSwagger.java
src/main/java/com/numble/team3/video/annotation/PutVideoSwagger.java
src/main/java/com/numble/team3/video/application/request/CreateOrUpdateVideoDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoListDto.java
src/main/java/com/numble/team3/video/controller/VideoController.java
src/main/java/com/numble/team3/video/resolver/SearchCondition.java

- resolved #83 
1. 관리자, 영상, 댓글 스웨거 문서를 작성했습니다.

[Docs] #83 스웨거 문서 작성

---

src/main/java/com/numble/team3/video/domain/enums/VideoCategory.java
src/main/java/com/numble/team3/video/domain/enums/VideoSortCondition.java
src/main/java/com/numble/team3/video/infra/JpaVideoSearchRepositoryImpl.java
src/main/java/com/numble/team3/video/resolver/SearchCondition.java
src/main/java/com/numble/team3/video/resolver/VideoQueryStringArgumentResolver.java

영상 카테고리 및 정렬 조건 추가합니다.
- resolved #87

[Feat] #87 영상 카테고리 및 정렬 조건 추가

---

src/main/java/com/numble/team3/like/application/LikeVideoService.java
src/main/java/com/numble/team3/like/controller/LikeVideoController.java
src/main/java/com/numble/team3/like/domain/LikeVideo.java
src/main/java/com/numble/team3/like/infra/CustomJpaLikeVideoRepositoryImpl.java
src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java
src/test/java/com/numble/team3/factory/entity/LikeVideoEntityFactory.java
src/test/java/com/numble/team3/like/application/LikeVideoServiceTest.java
src/test/java/com/numble/team3/like/controller/LikeVideoVideoControllerTest.java

- resolved #89 
- 좋아요(관심영상) 로직을 전반적으로 수정했습니다.
- `LikeVideo` 엔티티에 `VideoCategory category` 필드를 추가했습니다.
- `/api/likes/add`에서 추가적으로 `category`를 입력받도록 했습니다.
- 카테고리 조회 시 `Video Entity`의 `VideoCategory`가 아닌 `LikeVideo`의 `VideoCategory`로 조건을 수정했습니다.
- 변경에 영향을 받은 테스트 코드를 수정했습니다.

[refactor] #89 좋아요(관심영상) 추가, 조회 방식 변경

---

src/main/java/com/numble/team3/config/CorsConfig.java

- resolved #92 
- `cors` 관련 설정을 추가했습니다.
- 현 단계에서는 프론트엔드 로컬 PC - `ec2`와의 연동이므로 모든 `Origin`에 대해 허용으로 처리했습니다.
- `config/CorsConfig`에 설정을 추가했습니다.

[feat] #92 CORS 설정 추가

---

src/main/java/com/numble/team3/account/application/AccountService.java

- 사용자 정보 수정 시 닉네임은 수정하지 않고 그대로 유지하는 경우를 위한 로직 수정
- `AccountService.updateAccount`에서 `accountRepository.findByNickname`에 `filter`로 사용자 id가 같은 경우(닉네임을 수정하지 않은 경우)를 처리했습니다.
- `AccountService.updateAccount`에서 `accountRepository.findByNickname` 부분만 확인해주시면 될 것 같습니다.

[refactor] AccountService.updateAccount 로직 수정

---

src/main/java/com/numble/team3/config/CorsConfig.java

- CorsConfig 수정
- CorsConfig 수정

[refactor] CorsConfig 수정

---

src/main/java/com/numble/team3/account/annotation/GetMyAccountSwagger.java
src/main/java/com/numble/team3/admin/annotation/GetAccountSwagger.java
src/main/java/com/numble/team3/admin/annotation/GetAccountsSwagger.java
src/main/java/com/numble/team3/converter/annotation/ImageResizeSwagger.java
src/main/java/com/numble/team3/like/annotation/GetAllLikeVideosSwagger.java
src/main/java/com/numble/team3/like/annotation/GetLikeVideosByCategorySwagger.java
src/main/java/com/numble/team3/like/annotation/GetVideoRankByDayLikeSwagger.java

- Swagger Response 예시 수정
- Swagger Response 예시를 수정했습니다.
- `Account`
- `Admin`
- `Convert` - `Image`
- `Like`

[docs] Swagger Response 예시 수정

---

src/main/java/com/numble/team3/account/annotation/GetMyAccountDetailSwagger.java
src/main/java/com/numble/team3/account/annotation/GetMyVideosSwagger.java
src/main/java/com/numble/team3/account/application/AccountService.java
src/main/java/com/numble/team3/account/application/response/GetMyAccountDetailDto.java
src/main/java/com/numble/team3/account/application/response/GetMySimpleVideoDto.java
src/main/java/com/numble/team3/account/application/response/GetMyVideosDto.java
src/main/java/com/numble/team3/account/controller/AccountController.java
src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepository.java
src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java
src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java
src/main/resources/application.yml
src/test/java/com/numble/team3/account/application/AccountServiceTest.java

- resolved #90 
- 회원 정보 상세 조회 기능을 추가했습니다.
- 업로드 영상 조회 기능을 추가했습니다.
- 피그마를 기준으로 작업했습니다.
- `AccountController`
- `getMyAccountDetail`를 추가했습니다.
- `getMyVideos`를 추가했습니다.
- 관련된 `Swagger`를 추가했습니다.
- `AccountService`
- `getDetailAccountByUserInfo`를 추가했습니다.
- `getMyVideosDto`를 추가했습니다.
- 업로드 영상을 조회하기 위해 `JpaVideoRepository` 의존성을 추가했습니다.
- `VideoRepository`
- 페이징 처리를 위해 `JpaAccountVideoRepository`, `JpaAccountVideoRepositoryImpl`를 추가했습니다.
- `JpaVideoRepository`에 `findAllByAccountId`, `findAllByAccountIdAndLimit` 메소드를 추가했습니다.
- 변경 사항으로 인해 바뀐 테스트 코드를 수정하고, 새로운 기능에 대한 테스트 코드도 추가했습니다.
- `video/infra`패키지에 추가된 `Repository` 관련된 내용을 확인해주시면 감사하겠습니다!

[feat] #90 회원 정보 상세 조회, 업로드 영상 조회 기능 추가

---

src/main/java/com/numble/team3/config/SecurityConfig.java

- `CORS` 설정 변경
- `CORS` 설정을 스프링 시큐리티로 이동했습니다.

[refactor] CORS 설정 변경

---

src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/application/request/CreateOrUpdateVideoDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java
src/main/java/com/numble/team3/video/domain/Video.java

- resolved #104 
1. 동영상 도메인의 show_id는 더 이상 사용하지 않아 제거했습니다.
2. request dto에서 url 유효성 검사를 추가했습니다.
3. 변경 메서드에 동영상 url을 포함했습니다.

[feat] #104 동영상 도메인 리팩토링

---

src/main/java/com/numble/team3/video/domain/enums/VideoCategory.java

[bug] #106 카테고리 오타 수정

---

src/main/java/com/numble/team3/sign/controller/SignController.java

- `Cookie` 생성 옵션 변경
- `domain`을 `localhost`에서 `localhost:3000`으로 변경했습니다.
- `ResponseCookie`에서 포트를 지정할 수 없는 문제가 발생해 ec2의 퍼블릭 IPv4 주소로 변경했습니다.

[refactor] Cookie 생성 옵션 변경

---

src/main/java/com/numble/team3/admin/application/response/GetVideoDetailForAdminDto.java
src/main/java/com/numble/team3/comment/application/response/GetCommentDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoDto.java

1. localdatetime의 직렬화 포맷을 변경합니다.
- resolved #112

[bug] #112 dto localdatetime 포맷 변경

---

src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java

[bug] #119 영상 상세 조회 프로필 사진 경로 버그 수정

---

src/main/java/com/numble/team3/account/annotation/GetMyAccountDetailSwagger.java
src/main/java/com/numble/team3/account/annotation/GetMyAccountSwagger.java
src/main/java/com/numble/team3/account/annotation/GetMyVideosSwagger.java
src/main/java/com/numble/team3/account/annotation/UpdateMyAccountSwagger.java
src/main/java/com/numble/team3/account/annotation/WithdrawalAccountSwagger.java

- account 관련 `Swagger` 수정
- `AccountController`에서 사용되는 `Swagger`에 누락된 내용을 추가했습니다.

[docs] Account 관련 Swagger 수정

---

src/main/java/com/numble/team3/config/SecurityConfig.java
src/main/java/com/numble/team3/like/annotation/GetVideoRankByDayCategoryLikeSwagger.java
src/main/java/com/numble/team3/like/application/LikeVideoService.java
src/main/java/com/numble/team3/like/application/response/GetLikeVideoRankDto.java
src/main/java/com/numble/team3/like/controller/LikeVideoController.java
src/main/java/com/numble/team3/like/infra/CustomJpaLikeVideoRepositoryImpl.java

- resolved #126 
- 일일 랭킹 카테고리 별 조회 기능을 추가했습니다.

[feat] #126 일일 랭킹 카테고리 별 조회 기능 추가

---

src/main/java/com/numble/team3/account/resolver/LoginMethodArgumentResolver.java
src/main/java/com/numble/team3/video/infra/JpaVideoSearchRepositoryImpl.java

[feat] #128 로그인 하지 않고도 댓글 조회 가능하도록 수정, 영상 제목 검색 부분일치로 수정

---

src/main/java/com/numble/team3/converter/annotation/ImageResizeSwagger.java
src/main/java/com/numble/team3/sign/annotation/CreateAccessTokenSwagger.java

- `Swagger`에서 누락되었거나 변경된 로직에 대한 부분을 수정했습니다.
- `ImageConvert` 시 `Authorization` 헤더가 필요함을 명시
- `access token` 재발급 로직이 쿠키를 사용하지 않음으로써 변경된 내용을 명시
- `Authorization` 헤더에 `refresh token` 전달
- 헤더가 없거나 토큰이 만료된 경우 상태 코드 401 반환

[docs] Swagger 수정

---

src/main/java/com/numble/team3/comment/application/response/GetCommentDto.java
src/main/java/com/numble/team3/comment/application/response/GetCommentListDto.java

[docs] #132 댓글 조회 스웨거 문서 추가

---

src/main/java/com/numble/team3/admin/annotation/GetAccountVideosSwagger.java
src/main/java/com/numble/team3/admin/application/response/GetAccountVideosDto.java
src/main/java/com/numble/team3/admin/application/response/GetSimpleAccountVideoDto.java
src/main/java/com/numble/team3/admin/controller/AdminAccountController.java
src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java

- 관리자 회원 업로드 영상 목록 조회 기능 추가
- `JpaVideoRepository`에 메소드를 추가했습니다.
- `VideoService`에 메소드를 추가했습니다.
- `AdminAccountController`에 메소드를 추가했습니다.

[feat] 관리자 회원 업로드 영상 목록 조회 기능 추가

---

src/main/java/com/numble/team3/admin/application/response/GetVideoListForAdminDto.java

- GetVideoListForAdminDto 페이지 방식 변경
- `contents.getSize() + 1`으로 1페이지부터 시작이 되도록 설정했습니다.

[refactor] videos 페이지 수정

---

src/main/java/com/numble/team3/admin/application/response/GetAdminDeleteVideoStateDto.java
src/main/java/com/numble/team3/admin/application/response/GetVideoListForAdminDto.java
src/main/java/com/numble/team3/admin/controller/AdminVideoController.java
src/main/java/com/numble/team3/video/application/VideoService.java

[Fix] 관리자 동영상 삭제 시 state 내려주기, 계정이 올린 동영상 dto 타입 통일

---

src/main/java/com/numble/team3/admin/application/response/GetVideoListForAdminDto.java

- `GetVideoListForAdminDto` 페이지 적용 방식 변경
- `GetVideoListForAdminDto`에서 빌더 패턴에서 누락된 `nowPage`를 추가하고, 1을 더해 1페이지부터 시작할 수 있도록 처리했습니다.

[refactor] GetVideoListForAdminDto 현재 페이지 방식 변경

---

src/main/java/com/numble/team3/admin/application/response/GetSimpleAccountVideoDto.java
src/main/java/com/numble/team3/admin/application/response/GetVideoDetailForAdminDto.java
src/main/java/com/numble/team3/admin/application/response/GetVideoSimpleForAdminDto.java

[refactor] #139 관리자 영상 조회 시 관리자 영상 상태 조회

---

src/main/java/com/numble/team3/converter/infra/AwsConvertImageUtils.java

- Image Resize 과정 log 추가
- Image Resize 과정 중 오류가 발생해 이를 확인하기 위해 log를 추가했습니다.

[refactor] image resize log 추가

---

src/main/java/com/numble/team3/admin/application/response/GetVideoDetailForAdminDto.java

- `GetVideoDetailForAdminDto` `Field` 추가
- 프론트엔드 요청에 따라 `GetVideoDetailForAdminDto`에 `accountId` 필드를 추가했습니다.

[refactor] GetVideoDetailForAdminDto Field 추가

---

src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java

- `cross join` 해결
- `JpaAccountVideoRepositoryImpl` 에서 `join`을 명시적으로 추가해주었습니다.

[refactor] JpaAccountVideoRepositoryImpl cross join 해결

---

src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java

Reverts Numble3/Paws-Backend#144

[refactor] JpaAccountVideoRepositoryImpl  수정

---

src/main/java/com/numble/team3/account/application/AccountService.java
src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java

[refactor] getMyVideos 로직 수정

---

src/main/java/com/numble/team3/common/advice/CommonRestControllerAdvice.java

- `RestControllerAdvice` 수정
- 서버에서 발생하는 `500` 에러를 확인하기 위해 핸들링하지 못한 예외 발생 시 이를 응답에 반환하도록 했습니다.

[refactor] RestControllerAdvice 수정

---

src/main/java/com/numble/team3/admin/application/response/GetVideoDetailForAdminDto.java
src/main/java/com/numble/team3/converter/application/VideoConvertService.java
src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java
src/main/resources/application-ffmpeg.yml

Fix 150 동영상 시간 dto에 포함

---

src/main/java/com/numble/team3/account/annotation/GetMyAccountDetailSwagger.java
src/main/java/com/numble/team3/account/annotation/GetMyVideosSwagger.java
src/main/java/com/numble/team3/account/application/response/GetMySimpleVideoDto.java
src/main/java/com/numble/team3/video/application/response/GetVideoDto.java
src/main/java/com/numble/team3/video/domain/enums/VideoType.java
src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java

- 영상 관련 `Response`에 `VideoType` 추가
- `GetVideoDto`에 `videoType` 필드를 추가했습니다.
- `VideoType` `enum`에 `@JsonValue`를 추가했습니다.
- `GetMySimpleVideoDto`에 `videoType` 필드를 추가했습니다.
- 변경된 사항에 맞춰 `Swagger`를 수정했습니다.

[refactor] Response VideoType 추가

---

src/main/java/com/numble/team3/video/application/response/GetVideoDto.java

- `GetVideoDto` 누락 수정
- `videoType` `field` 추가로 인해 생성자를 변경했습니다.

[refactor] GetVideoDto 누락 수정

---

src/main/java/com/numble/team3/config/SecurityConfig.java

- `cors` 설정 추가
- 관리자 배포 사이트에 대한 `cors` 설정을 추가했습니다.

[refactor] cors 설정 추가

---

src/main/java/com/numble/team3/converter/application/VideoConvertService.java
src/main/java/com/numble/team3/converter/domain/ConvertVideoUtils.java
src/main/java/com/numble/team3/converter/infra/VideoFfmpegUtils.java
src/main/java/com/numble/team3/video/infra/JpaVideoSearchRepositoryImpl.java
src/main/java/com/numble/team3/video/resolver/SearchCondition.java
src/main/resources/application-ffmpeg.yml
src/test/java/com/numble/team3/Team3ApplicationTests.java

Bug 149 변환 디렉토리 설정 변경 및 동영상 시간 버그 수정

---

src/main/resources/application-ffmpeg.yml

[bug] #149 경로 다시 변경

---

src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java

- `getMyVideoDtos` 로직 수정
- `getMyVideoDtos`에서 누락되어있던 `accountId`에 대한 조건을 추가했습니다.

[refactor] getMyVideoDtos 로직 수정

---

src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java

- `findAllByAccountIdWithAdmin` 수정
- `findAllByAccountIdWithAdmin`의 `@Query`에 삭제되지 않은 영상만 조회되도록 조건을 추가했습니다.

[refactor] findAllByAccountIdWithAdmin 수정

---

src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java

Reverts Numble3/Paws-Backend#166

[refactor] findAllByAccountIdWithAdmin 수정 복구

---

src/main/java/com/numble/team3/video/infra/JpaVideoRepository.java

- `/api/accounts/detail` 삭제한 영상 제외
- `JpaVideoRepository. findAllByAccountId` 메소드 `@Query`에 삭제한 영상을 제외하는 조건문을 추가했습니다.

[refactor] findAllByAccountId 수정

---

src/main/java/com/numble/team3/config/SecurityConfig.java

- `cors` `origin` 추가
- 프론트 엔드 관리자 배포 url을 `origin`에 추가했습니다.

[refactor] cors origin 추가

---

src/main/java/com/numble/team3/config/SecurityConfig.java

- `cors` `origin` 추가
- 프론트 엔드 url을 `cors`에 추가했습니다.

[refactor] cors front origin 추가

---

src/main/java/com/numble/team3/converter/application/VideoConvertService.java
src/main/java/com/numble/team3/converter/controller/ConvertController.java
src/main/java/com/numble/team3/converter/domain/ConvertVideoUtils.java
src/test/java/com/numble/team3/converter/domain/ConvertVideoUtilsTest.java
src/test/java/com/numble/team3/factory/VideoFfmpegUtilsFactory.java

[feat] #176 동영상 변환 Cloud Front 연동

---

src/main/java/com/numble/team3/converter/application/VideoConvertService.java

[feat] #178 S3 업로드 키 명명 방식 변경

---

src/main/java/com/numble/team3/video/infra/JpaAccountVideoRepositoryImpl.java

- #173 
- `GetVideoDto` 필드 변경으로 인한 `getMyVideoDtos` 메소드 로직 변경
- `JpaAccountVideoRepositoryImpl.getMyVideoDtos()`의 `Projections.constructor`에 `GetVideoDto` 생성자에 추가된 필드까지 저장하도록 수정했습니다.

[refactor] getMyVideoDtos 수정

---

src/main/java/com/numble/team3/like/annotation/GetLikeVideosByCategorySwagger.java

- `GetLikeVideosByCategorySwagger` 수정
- `GetVideoDto` 변경으로 인한 수정사항과 누락된 부분을 추가했습니다.

[refactor] GetLikeVideosByCategorySwagger 수정

---

src/main/java/com/numble/team3/like/application/response/GetLikeListDto.java

- `GetLikeListDto` 수정
- `GetLikeListDto`에서 다음 페이지가 없을 시 `lastLikeId`가 출력되지 않도록 했는데 명확하게 다음 페이지가 없는 것을 표현하기 위해 다음 페이지가 없을 경우(lastLikeId가 `null`인 경우)에도 `lastLikeId`를 출력하도록 수정했습니다.

[refactor] GetLikeListDto 수정

---

src/main/java/com/numble/team3/like/controller/LikeVideoController.java
src/main/java/com/numble/team3/like/infra/CustomJpaLikeVideoRepositoryImpl.java

- `getLikesByCategory` 수정
- 프론트엔드의 요청에 따라 `getLikesByCategory` 메소드에서 `likeId`가 `null`이거나 `0`일 때 1페이지를 조회할 수 있도록 변경했습니다.

[refactor] getLikesByCategory 수정

---

src/main/java/com/numble/team3/converter/application/advice/ConvertRestControllerAdvice.java
src/main/java/com/numble/team3/converter/application/request/CreateVideoDto.java
src/main/java/com/numble/team3/converter/controller/ConvertController.java
src/main/java/com/numble/team3/video/advice/VideoRestControllerAdvice.java
src/main/java/com/numble/team3/video/controller/VideoController.java

[feat] #188 비디오, 변환 컨트롤러 advice 예외 추가

---

src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java

- `existsLikeByVideoIdAndAccountId` 메소드 수정
- `existsLikeByVideoIdAndAccountId` 메소드의 반환값을 수정했습니다.

[refactor] existsLikeByVideoIdAndAccountId 수정

---

src/main/java/com/numble/team3/like/application/LikeVideoService.java
src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java

- `addLike` 검증 로직 수정
- `exists`를 사용하던 방식에서 `Optional<Entity>`를 사용하는 방식으로 변경했습니다.

[refactor] addLike 검증 로직 수정

---

src/main/java/com/numble/team3/converter/application/VideoConvertService.java
src/main/java/com/numble/team3/video/application/VideoService.java
src/main/java/com/numble/team3/video/application/response/GetVideoDetailDto.java

실수로 재귀문을 올렸음..
- resolved #194

feat #193 버그 수정

---

src/main/java/com/numble/team3/config/SecurityConfig.java
src/main/java/com/numble/team3/converter/controller/ConvertController.java

[bug] #196 동영상 파일 타입 수정

---

src/main/java/com/numble/team3/like/annotation/AddLikeVideoSwagger.java
src/main/java/com/numble/team3/like/annotation/DeleteLikeVideoSwagger.java
src/main/java/com/numble/team3/like/application/LikeVideoService.java
src/main/java/com/numble/team3/like/controller/LikeVideoController.java
src/main/java/com/numble/team3/video/domain/Video.java
src/test/java/com/numble/team3/like/controller/LikeVideoVideoControllerTest.java

- 좋아요 추가/삭제 시 로직 변경
- 좋아요 선택 시 DB에 저장된 `tb_video` 테이블의 `like`를 직접 변경하도록 수정했습니다.

[refactor] 좋아요 추가/삭제 시 로직 변경

---

src/main/java/com/numble/team3/like/infra/JpaLikeVideoRepository.java

- `JpaLikeVideoRepository` 수정
- `JPA`의 동일성 보장으로 인해 발생하는 데이터 동기화 문제를 해결하기 위해 `@Modifying` 애노테이션을 추가했습니다.

[refactor] JpaLikeVideoRepository 수정
